version: "3.9"
services:
  ice_breaker:
    command: "python ice_breaker.py"
    # command: "touch /app/output/ice_breaker.txt"
    build: .
    ports:
      - "8000:5000"
    volumes:
      - .:/app
      - ./output:/app/output